Traceback (most recent call last):
  File "C:\Users\nazim\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\nazim\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nazim\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nazim\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\nazim\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\nazim\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\nazim\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Ensure the image is loaded correctly
if img1 is None:
	raise ValueError("Image not loaded. Please check the file path.")

# Perform OCR on the image
results = reader.readtext(img1, detail=1, paragraph=True)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Cell [1;32mIn[7], line 3[0m
[0;32m      1[0m [38;5;66;03m# Ensure the image is loaded correctly[39;00m
[0;32m      2[0m [38;5;28;01mif[39;00m img1 [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m----> 3[0m 	[38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mImage not loaded. Please check the file path.[39m[38;5;124m"[39m)
[0;32m      5[0m [38;5;66;03m# Perform OCR on the image[39;00m
[0;32m      6[0m results [38;5;241m=[39m reader[38;5;241m.[39mreadtext(img1, detail[38;5;241m=[39m[38;5;241m1[39m, paragraph[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

[1;31mValueError[0m: Image not loaded. Please check the file path.

